### ISSUE TITLE
Update Burkina Faso data on FDW and GSCD

### ISSUE THREAD

**Issue by gnodnooh** [chc-ucsb/Harvestat#12]
New data is uploaded to FDW via helpdesk ticket: https://fewsnet.atlassian.net/browse/HELP-2255?atlOrigin=eyJpIjoiNmJhN2JmZDA1ZDVjNDExYWJkMzExYWM1YjdlZDRhM2YiLCJwIjoiaiJ9

Also, I manually added to GSCD side. If FDW updates the new data, GDCS code will make the duplicated error, so we can notice it.

**Comment by WestonAnderson** [comment]
I'm closing this ticket because of the other BF ticket in our "issues"
